# Generated by Django 3.0.7 on 2020-07-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
