# Generated by Django 3.0.7 on 2020-07-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200722_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='district',
            new_name='state',
        ),
    ]
