# Generated by Django 3.0.8 on 2020-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200722_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, null=True)),
                ('categories', models.ManyToManyField(to='Main.Tags')),
            ],
        ),
    ]
