# Generated by Django 3.0.8 on 2020-07-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='castregister',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='cast',
        ),
    ]
