# Generated by Django 3.0.8 on 2020-07-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200725_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castregister',
            old_name='audition_date',
            new_name='expire',
        ),
    ]
