# Generated by Django 3.0.8 on 2020-07-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200725_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='castregister',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
