# Generated by Django 3.0.8 on 2020-07-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_castregister_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castregister',
            name='description',
        ),
        migrations.AddField(
            model_name='castregister',
            name='castcall_image',
            field=models.ImageField(null=True, upload_to='castcall'),
        ),
        migrations.AddField(
            model_name='castregister',
            name='production_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='castregister',
            name='role_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='castregister',
            name='role',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
