# Generated by Django 3.0.8 on 2020-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200725_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmpromotion',
            name='location',
        ),
        migrations.RemoveField(
            model_name='filmpromotion',
            name='promotion_image',
        ),
        migrations.AddField(
            model_name='filmpromotion',
            name='category',
            field=models.ManyToManyField(to='Main.Tags'),
        ),
        migrations.AddField(
            model_name='filmpromotion',
            name='promotion_video',
            field=models.FileField(null='True', upload_to='promotionvideos'),
            preserve_default='True',
        ),
    ]
